### ISSUE TITLE
The chatbot is not working. Can you please look ?

### ISSUE THREAD

**Issue by PriomDeb** [pandeyanuradha/Chatbot-for-mental-health#1]
Hi, I was trying your source codes from Chatbot for mental health. But the chatbot is not working and throwing error from decode function. I am attaching a screenshot. If you have time can you please check it ? 

https://i.ibb.co/RY7HNPg/Screenshot-2022-12-13-013015.png 
https://i.ibb.co/xXVXd01/Screenshot-2022-12-13-013410.png

Regards,
Priom Deb

**Comment by pandeyanuradha** [comment]
I have updated the repository with the latest working scripts.
